name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Cloning the code"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Build using docker" 
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "Testing the code"

  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploying the code
        run: echo "deploy the code"
    
